/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.4.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionNew_File;
    QAction *actionSave_File;
    QAction *actionLoad_File;
    QAction *actionExit;
    QAction *actionHelp;
    QAction *actionUser_Manual;
    QWidget *centralWidget;
    QGroupBox *CPUGroup;
    QGroupBox *ACGroup;
    QLineEdit *AC1;
    QLineEdit *AC2;
    QLineEdit *AC3;
    QLineEdit *AC4;
    QGroupBox *IRGroup;
    QLineEdit *IR1;
    QLineEdit *IR2;
    QLineEdit *IR3;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout;
    QPushButton *runBtn;
    QPushButton *stepBtn;
    QPushButton *clearCPUBut;
    QPushButton *clearAllBut;
    QGroupBox *PCGroup;
    QLineEdit *PC1;
    QLineEdit *PC2;
    QGroupBox *InputGroup;
    QLineEdit *IC1;
    QLineEdit *IC2;
    QLineEdit *IC3;
    QLineEdit *IC4;
    QLineEdit *IC5;
    QLineEdit *IC6;
    QLineEdit *IC7;
    QLineEdit *IC8;
    QLineEdit *IC9;
    QLineEdit *IC10;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QPushButton *resetInBtn;
    QPushButton *clearInBut;
    QGroupBox *OutputGroup;
    QLineEdit *OC1;
    QLineEdit *OC2;
    QLineEdit *OC3;
    QLineEdit *OC4;
    QLineEdit *OC5;
    QLineEdit *OC6;
    QLineEdit *OC7;
    QLineEdit *OC8;
    QLineEdit *OC9;
    QLineEdit *OC10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QPushButton *clearOutBut;
    QGroupBox *memoryGroup;
    QLineEdit *mem1;
    QLineEdit *mem2;
    QLineEdit *mem5;
    QLineEdit *mem0;
    QLineEdit *mem6;
    QLineEdit *mem9;
    QLineEdit *mem4;
    QLineEdit *mem3;
    QLineEdit *mem8;
    QLineEdit *mem7;
    QLineEdit *mem11;
    QLineEdit *mem12;
    QLineEdit *mem15;
    QLineEdit *mem10;
    QLineEdit *mem16;
    QLineEdit *mem19;
    QLineEdit *mem14;
    QLineEdit *mem13;
    QLineEdit *mem18;
    QLineEdit *mem17;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLineEdit *mem25;
    QLineEdit *mem39;
    QLineEdit *mem36;
    QLineEdit *mem21;
    QLabel *label_51;
    QLineEdit *mem31;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLineEdit *mem34;
    QLabel *label_55;
    QLineEdit *mem22;
    QLineEdit *mem29;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLineEdit *mem35;
    QLineEdit *mem28;
    QLabel *label_60;
    QLineEdit *mem27;
    QLabel *label_61;
    QLabel *label_62;
    QLineEdit *mem38;
    QLineEdit *mem26;
    QLabel *label_63;
    QLabel *label_64;
    QLineEdit *mem33;
    QLineEdit *mem20;
    QLabel *label_65;
    QLineEdit *mem37;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_68;
    QLineEdit *mem23;
    QLabel *label_69;
    QLineEdit *mem24;
    QLineEdit *mem30;
    QLineEdit *mem32;
    QLabel *label_70;
    QLineEdit *mem40;
    QLabel *label_71;
    QLabel *label_72;
    QLabel *label_73;
    QLineEdit *mem49;
    QLineEdit *mem47;
    QLineEdit *mem42;
    QLineEdit *mem48;
    QLabel *label_74;
    QLineEdit *mem57;
    QLineEdit *mem46;
    QLineEdit *mem50;
    QLabel *label_75;
    QLabel *label_76;
    QLineEdit *mem52;
    QLabel *label_77;
    QLineEdit *mem44;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QLineEdit *mem41;
    QLabel *label_81;
    QLineEdit *mem55;
    QLabel *label_82;
    QLineEdit *mem59;
    QLineEdit *mem53;
    QLineEdit *mem58;
    QLabel *label_83;
    QLineEdit *mem51;
    QLabel *label_84;
    QLabel *label_85;
    QLineEdit *mem56;
    QLineEdit *mem54;
    QLabel *label_86;
    QLabel *label_87;
    QLineEdit *mem45;
    QLabel *label_88;
    QLabel *label_89;
    QLineEdit *mem43;
    QLabel *label_90;
    QLineEdit *mem60;
    QLabel *label_91;
    QLabel *label_92;
    QLineEdit *mem71;
    QLabel *label_93;
    QLabel *label_94;
    QLabel *label_95;
    QLineEdit *mem63;
    QLabel *label_96;
    QLineEdit *mem62;
    QLabel *label_97;
    QLabel *label_98;
    QLabel *label_99;
    QLabel *label_100;
    QLineEdit *mem76;
    QLineEdit *mem72;
    QLineEdit *mem70;
    QLabel *label_101;
    QLineEdit *mem68;
    QLabel *label_102;
    QLabel *label_103;
    QLineEdit *mem67;
    QLineEdit *mem66;
    QLineEdit *mem74;
    QLineEdit *mem77;
    QLineEdit *mem65;
    QLabel *label_104;
    QLabel *label_105;
    QLineEdit *mem75;
    QLineEdit *mem78;
    QLabel *label_106;
    QLabel *label_107;
    QLineEdit *mem79;
    QLabel *label_108;
    QLineEdit *mem61;
    QLabel *label_109;
    QLineEdit *mem73;
    QLineEdit *mem64;
    QLabel *label_110;
    QLineEdit *mem69;
    QLineEdit *mem84;
    QLineEdit *mem91;
    QLineEdit *mem85;
    QLabel *label_111;
    QLineEdit *mem90;
    QLineEdit *mem87;
    QLineEdit *mem88;
    QLineEdit *mem81;
    QLabel *label_112;
    QLabel *label_113;
    QLabel *label_114;
    QLineEdit *mem94;
    QLineEdit *mem93;
    QLabel *label_115;
    QLabel *label_116;
    QLabel *label_117;
    QLabel *label_118;
    QLineEdit *mem99;
    QLineEdit *mem92;
    QLabel *label_119;
    QLineEdit *mem80;
    QLabel *label_120;
    QLineEdit *mem95;
    QLabel *label_121;
    QLabel *label_122;
    QLabel *label_123;
    QLineEdit *mem98;
    QLabel *label_124;
    QLabel *label_125;
    QLabel *label_126;
    QLineEdit *mem83;
    QLineEdit *mem97;
    QLineEdit *mem96;
    QLabel *label_127;
    QLineEdit *mem89;
    QLabel *label_128;
    QLineEdit *mem86;
    QLabel *label_129;
    QLineEdit *mem82;
    QLabel *label_130;
    QPushButton *clearMemBut;
    QLabel *label_131;
    QWidget *saveLoadWidget;
    QPushButton *okButton;
    QPushButton *cancelButton;
    QLineEdit *fileNameInput;
    QLabel *label_21;
    QMenuBar *menuBar;
    QMenu *fileMenu;
    QMenu *helpMenu;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(835, 705);
        actionNew_File = new QAction(MainWindow);
        actionNew_File->setObjectName(QStringLiteral("actionNew_File"));
        actionSave_File = new QAction(MainWindow);
        actionSave_File->setObjectName(QStringLiteral("actionSave_File"));
        actionLoad_File = new QAction(MainWindow);
        actionLoad_File->setObjectName(QStringLiteral("actionLoad_File"));
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QStringLiteral("actionExit"));
        actionHelp = new QAction(MainWindow);
        actionHelp->setObjectName(QStringLiteral("actionHelp"));
        actionUser_Manual = new QAction(MainWindow);
        actionUser_Manual->setObjectName(QStringLiteral("actionUser_Manual"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        CPUGroup = new QGroupBox(centralWidget);
        CPUGroup->setObjectName(QStringLiteral("CPUGroup"));
        CPUGroup->setGeometry(QRect(280, 10, 461, 101));
        ACGroup = new QGroupBox(CPUGroup);
        ACGroup->setObjectName(QStringLiteral("ACGroup"));
        ACGroup->setGeometry(QRect(40, 10, 121, 51));
        AC1 = new QLineEdit(ACGroup);
        AC1->setObjectName(QStringLiteral("AC1"));
        AC1->setGeometry(QRect(10, 20, 25, 25));
        AC1->setInputMethodHints(Qt::ImhNone);
        AC1->setReadOnly(true);
        AC2 = new QLineEdit(ACGroup);
        AC2->setObjectName(QStringLiteral("AC2"));
        AC2->setGeometry(QRect(35, 20, 25, 25));
        AC2->setInputMethodHints(Qt::ImhNone);
        AC2->setReadOnly(true);
        AC3 = new QLineEdit(ACGroup);
        AC3->setObjectName(QStringLiteral("AC3"));
        AC3->setGeometry(QRect(60, 20, 25, 25));
        AC3->setInputMethodHints(Qt::ImhNone);
        AC3->setReadOnly(true);
        AC4 = new QLineEdit(ACGroup);
        AC4->setObjectName(QStringLiteral("AC4"));
        AC4->setGeometry(QRect(85, 20, 25, 25));
        AC4->setInputMethodHints(Qt::ImhNone);
        AC4->setReadOnly(true);
        IRGroup = new QGroupBox(CPUGroup);
        IRGroup->setObjectName(QStringLiteral("IRGroup"));
        IRGroup->setGeometry(QRect(340, 10, 91, 51));
        IR1 = new QLineEdit(IRGroup);
        IR1->setObjectName(QStringLiteral("IR1"));
        IR1->setGeometry(QRect(10, 20, 25, 25));
        IR1->setInputMethodHints(Qt::ImhNone);
        IR1->setReadOnly(true);
        IR2 = new QLineEdit(IRGroup);
        IR2->setObjectName(QStringLiteral("IR2"));
        IR2->setGeometry(QRect(35, 20, 25, 25));
        IR2->setInputMethodHints(Qt::ImhNone);
        IR2->setReadOnly(true);
        IR3 = new QLineEdit(IRGroup);
        IR3->setObjectName(QStringLiteral("IR3"));
        IR3->setGeometry(QRect(60, 20, 25, 25));
        IR3->setInputMethodHints(Qt::ImhNone);
        IR3->setReadOnly(true);
        layoutWidget = new QWidget(CPUGroup);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(90, 70, 320, 25));
        horizontalLayout = new QHBoxLayout(layoutWidget);
        horizontalLayout->setSpacing(6);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        runBtn = new QPushButton(layoutWidget);
        runBtn->setObjectName(QStringLiteral("runBtn"));

        horizontalLayout->addWidget(runBtn);

        stepBtn = new QPushButton(layoutWidget);
        stepBtn->setObjectName(QStringLiteral("stepBtn"));

        horizontalLayout->addWidget(stepBtn);

        clearCPUBut = new QPushButton(layoutWidget);
        clearCPUBut->setObjectName(QStringLiteral("clearCPUBut"));

        horizontalLayout->addWidget(clearCPUBut);

        clearAllBut = new QPushButton(layoutWidget);
        clearAllBut->setObjectName(QStringLiteral("clearAllBut"));

        horizontalLayout->addWidget(clearAllBut);

        PCGroup = new QGroupBox(CPUGroup);
        PCGroup->setObjectName(QStringLiteral("PCGroup"));
        PCGroup->setGeometry(QRect(220, 10, 71, 51));
        PC1 = new QLineEdit(PCGroup);
        PC1->setObjectName(QStringLiteral("PC1"));
        PC1->setGeometry(QRect(10, 20, 25, 25));
        PC1->setInputMethodHints(Qt::ImhNone);
        PC1->setReadOnly(false);
        PC2 = new QLineEdit(PCGroup);
        PC2->setObjectName(QStringLiteral("PC2"));
        PC2->setGeometry(QRect(35, 20, 25, 25));
        PC2->setInputMethodHints(Qt::ImhNone);
        PC2->setReadOnly(false);
        InputGroup = new QGroupBox(centralWidget);
        InputGroup->setObjectName(QStringLiteral("InputGroup"));
        InputGroup->setGeometry(QRect(50, 90, 101, 291));
        IC1 = new QLineEdit(InputGroup);
        IC1->setObjectName(QStringLiteral("IC1"));
        IC1->setGeometry(QRect(30, 20, 50, 20));
        QFont font;
        font.setPointSize(10);
        IC1->setFont(font);
        IC2 = new QLineEdit(InputGroup);
        IC2->setObjectName(QStringLiteral("IC2"));
        IC2->setGeometry(QRect(30, 40, 50, 20));
        IC2->setFont(font);
        IC3 = new QLineEdit(InputGroup);
        IC3->setObjectName(QStringLiteral("IC3"));
        IC3->setGeometry(QRect(30, 60, 50, 20));
        IC3->setFont(font);
        IC4 = new QLineEdit(InputGroup);
        IC4->setObjectName(QStringLiteral("IC4"));
        IC4->setGeometry(QRect(30, 80, 50, 20));
        IC4->setFont(font);
        IC5 = new QLineEdit(InputGroup);
        IC5->setObjectName(QStringLiteral("IC5"));
        IC5->setGeometry(QRect(30, 100, 50, 20));
        IC5->setFont(font);
        IC6 = new QLineEdit(InputGroup);
        IC6->setObjectName(QStringLiteral("IC6"));
        IC6->setGeometry(QRect(30, 120, 50, 20));
        IC6->setFont(font);
        IC7 = new QLineEdit(InputGroup);
        IC7->setObjectName(QStringLiteral("IC7"));
        IC7->setGeometry(QRect(30, 140, 50, 21));
        IC7->setFont(font);
        IC8 = new QLineEdit(InputGroup);
        IC8->setObjectName(QStringLiteral("IC8"));
        IC8->setGeometry(QRect(30, 160, 50, 21));
        IC8->setFont(font);
        IC9 = new QLineEdit(InputGroup);
        IC9->setObjectName(QStringLiteral("IC9"));
        IC9->setGeometry(QRect(30, 180, 50, 20));
        IC9->setFont(font);
        IC10 = new QLineEdit(InputGroup);
        IC10->setObjectName(QStringLiteral("IC10"));
        IC10->setGeometry(QRect(30, 200, 50, 20));
        IC10->setFont(font);
        label = new QLabel(InputGroup);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 20, 15, 20));
        label_2 = new QLabel(InputGroup);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 40, 15, 20));
        label_3 = new QLabel(InputGroup);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 60, 15, 20));
        label_4 = new QLabel(InputGroup);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 80, 15, 20));
        label_5 = new QLabel(InputGroup);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 100, 15, 20));
        label_6 = new QLabel(InputGroup);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 120, 15, 20));
        label_7 = new QLabel(InputGroup);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 140, 15, 20));
        label_8 = new QLabel(InputGroup);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 160, 15, 20));
        label_9 = new QLabel(InputGroup);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 180, 15, 20));
        label_10 = new QLabel(InputGroup);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 200, 15, 20));
        resetInBtn = new QPushButton(InputGroup);
        resetInBtn->setObjectName(QStringLiteral("resetInBtn"));
        resetInBtn->setGeometry(QRect(20, 230, 71, 21));
        QFont font1;
        font1.setPointSize(8);
        font1.setBold(false);
        font1.setWeight(50);
        resetInBtn->setFont(font1);
        clearInBut = new QPushButton(InputGroup);
        clearInBut->setObjectName(QStringLiteral("clearInBut"));
        clearInBut->setGeometry(QRect(20, 260, 71, 21));
        clearInBut->setFont(font1);
        IC1->raise();
        IC2->raise();
        IC3->raise();
        IC4->raise();
        IC5->raise();
        IC6->raise();
        IC7->raise();
        IC8->raise();
        IC9->raise();
        IC10->raise();
        label->raise();
        label_2->raise();
        label_3->raise();
        label_4->raise();
        label_5->raise();
        label_6->raise();
        label_7->raise();
        label_8->raise();
        label_9->raise();
        label_10->raise();
        resetInBtn->raise();
        clearInBut->raise();
        OutputGroup = new QGroupBox(centralWidget);
        OutputGroup->setObjectName(QStringLiteral("OutputGroup"));
        OutputGroup->setGeometry(QRect(50, 390, 101, 261));
        OC1 = new QLineEdit(OutputGroup);
        OC1->setObjectName(QStringLiteral("OC1"));
        OC1->setGeometry(QRect(30, 20, 50, 20));
        OC1->setFont(font);
        OC1->setReadOnly(true);
        OC2 = new QLineEdit(OutputGroup);
        OC2->setObjectName(QStringLiteral("OC2"));
        OC2->setGeometry(QRect(30, 40, 50, 20));
        OC2->setFont(font);
        OC2->setReadOnly(true);
        OC3 = new QLineEdit(OutputGroup);
        OC3->setObjectName(QStringLiteral("OC3"));
        OC3->setGeometry(QRect(30, 60, 50, 20));
        OC3->setFont(font);
        OC3->setReadOnly(true);
        OC4 = new QLineEdit(OutputGroup);
        OC4->setObjectName(QStringLiteral("OC4"));
        OC4->setGeometry(QRect(30, 80, 50, 20));
        OC4->setFont(font);
        OC4->setReadOnly(true);
        OC5 = new QLineEdit(OutputGroup);
        OC5->setObjectName(QStringLiteral("OC5"));
        OC5->setGeometry(QRect(30, 100, 50, 20));
        OC5->setFont(font);
        OC5->setReadOnly(true);
        OC6 = new QLineEdit(OutputGroup);
        OC6->setObjectName(QStringLiteral("OC6"));
        OC6->setGeometry(QRect(30, 120, 50, 20));
        OC6->setFont(font);
        OC6->setReadOnly(true);
        OC7 = new QLineEdit(OutputGroup);
        OC7->setObjectName(QStringLiteral("OC7"));
        OC7->setGeometry(QRect(30, 140, 50, 21));
        OC7->setFont(font);
        OC7->setReadOnly(true);
        OC8 = new QLineEdit(OutputGroup);
        OC8->setObjectName(QStringLiteral("OC8"));
        OC8->setGeometry(QRect(30, 160, 50, 20));
        OC8->setFont(font);
        OC8->setReadOnly(true);
        OC9 = new QLineEdit(OutputGroup);
        OC9->setObjectName(QStringLiteral("OC9"));
        OC9->setGeometry(QRect(30, 180, 50, 20));
        OC9->setFont(font);
        OC9->setReadOnly(true);
        OC10 = new QLineEdit(OutputGroup);
        OC10->setObjectName(QStringLiteral("OC10"));
        OC10->setGeometry(QRect(30, 200, 50, 20));
        OC10->setFont(font);
        OC10->setReadOnly(true);
        label_11 = new QLabel(OutputGroup);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 20, 15, 20));
        label_12 = new QLabel(OutputGroup);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 40, 15, 20));
        label_13 = new QLabel(OutputGroup);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 60, 15, 20));
        label_14 = new QLabel(OutputGroup);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 80, 15, 20));
        label_15 = new QLabel(OutputGroup);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 100, 15, 20));
        label_16 = new QLabel(OutputGroup);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 120, 15, 20));
        label_17 = new QLabel(OutputGroup);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(10, 140, 15, 20));
        label_18 = new QLabel(OutputGroup);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 160, 15, 20));
        label_19 = new QLabel(OutputGroup);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 180, 15, 20));
        label_20 = new QLabel(OutputGroup);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 200, 15, 20));
        clearOutBut = new QPushButton(OutputGroup);
        clearOutBut->setObjectName(QStringLiteral("clearOutBut"));
        clearOutBut->setGeometry(QRect(10, 230, 81, 21));
        clearOutBut->setFont(font1);
        memoryGroup = new QGroupBox(centralWidget);
        memoryGroup->setObjectName(QStringLiteral("memoryGroup"));
        memoryGroup->setGeometry(QRect(230, 120, 581, 471));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(true);
        font2.setWeight(75);
        memoryGroup->setFont(font2);
        mem1 = new QLineEdit(memoryGroup);
        mem1->setObjectName(QStringLiteral("mem1"));
        mem1->setGeometry(QRect(50, 50, 50, 20));
        QFont font3;
        font3.setPointSize(10);
        font3.setBold(false);
        font3.setWeight(50);
        mem1->setFont(font3);
        mem1->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem1->setAlignment(Qt::AlignCenter);
        mem2 = new QLineEdit(memoryGroup);
        mem2->setObjectName(QStringLiteral("mem2"));
        mem2->setGeometry(QRect(50, 70, 50, 20));
        mem2->setFont(font3);
        mem2->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem2->setAlignment(Qt::AlignCenter);
        mem5 = new QLineEdit(memoryGroup);
        mem5->setObjectName(QStringLiteral("mem5"));
        mem5->setGeometry(QRect(50, 130, 50, 20));
        mem5->setFont(font3);
        mem5->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem5->setAlignment(Qt::AlignCenter);
        mem0 = new QLineEdit(memoryGroup);
        mem0->setObjectName(QStringLiteral("mem0"));
        mem0->setGeometry(QRect(50, 30, 50, 20));
        mem0->setFont(font3);
        mem0->setInputMethodHints(Qt::ImhDigitsOnly);
        mem0->setAlignment(Qt::AlignCenter);
        mem0->setReadOnly(true);
        mem6 = new QLineEdit(memoryGroup);
        mem6->setObjectName(QStringLiteral("mem6"));
        mem6->setGeometry(QRect(50, 150, 50, 21));
        mem6->setFont(font3);
        mem6->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem6->setAlignment(Qt::AlignCenter);
        mem9 = new QLineEdit(memoryGroup);
        mem9->setObjectName(QStringLiteral("mem9"));
        mem9->setGeometry(QRect(50, 210, 50, 20));
        mem9->setFont(font3);
        mem9->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem9->setAlignment(Qt::AlignCenter);
        mem4 = new QLineEdit(memoryGroup);
        mem4->setObjectName(QStringLiteral("mem4"));
        mem4->setGeometry(QRect(50, 110, 50, 20));
        mem4->setFont(font3);
        mem4->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem4->setAlignment(Qt::AlignCenter);
        mem4->setReadOnly(false);
        mem3 = new QLineEdit(memoryGroup);
        mem3->setObjectName(QStringLiteral("mem3"));
        mem3->setGeometry(QRect(50, 90, 50, 20));
        mem3->setFont(font3);
        mem3->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem3->setAlignment(Qt::AlignCenter);
        mem8 = new QLineEdit(memoryGroup);
        mem8->setObjectName(QStringLiteral("mem8"));
        mem8->setGeometry(QRect(50, 190, 50, 20));
        mem8->setFont(font3);
        mem8->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem8->setAlignment(Qt::AlignCenter);
        mem7 = new QLineEdit(memoryGroup);
        mem7->setObjectName(QStringLiteral("mem7"));
        mem7->setGeometry(QRect(50, 170, 50, 20));
        mem7->setFont(font3);
        mem7->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem7->setAlignment(Qt::AlignCenter);
        mem11 = new QLineEdit(memoryGroup);
        mem11->setObjectName(QStringLiteral("mem11"));
        mem11->setGeometry(QRect(50, 250, 50, 20));
        mem11->setFont(font3);
        mem11->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem11->setAlignment(Qt::AlignCenter);
        mem12 = new QLineEdit(memoryGroup);
        mem12->setObjectName(QStringLiteral("mem12"));
        mem12->setGeometry(QRect(50, 270, 50, 20));
        mem12->setFont(font3);
        mem12->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem12->setAlignment(Qt::AlignCenter);
        mem15 = new QLineEdit(memoryGroup);
        mem15->setObjectName(QStringLiteral("mem15"));
        mem15->setGeometry(QRect(50, 330, 50, 20));
        mem15->setFont(font3);
        mem15->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem15->setAlignment(Qt::AlignCenter);
        mem10 = new QLineEdit(memoryGroup);
        mem10->setObjectName(QStringLiteral("mem10"));
        mem10->setGeometry(QRect(50, 230, 50, 20));
        mem10->setFont(font3);
        mem10->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem10->setAlignment(Qt::AlignCenter);
        mem16 = new QLineEdit(memoryGroup);
        mem16->setObjectName(QStringLiteral("mem16"));
        mem16->setGeometry(QRect(50, 350, 50, 21));
        mem16->setFont(font3);
        mem16->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem16->setAlignment(Qt::AlignCenter);
        mem19 = new QLineEdit(memoryGroup);
        mem19->setObjectName(QStringLiteral("mem19"));
        mem19->setGeometry(QRect(50, 410, 50, 20));
        mem19->setFont(font3);
        mem19->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem19->setAlignment(Qt::AlignCenter);
        mem14 = new QLineEdit(memoryGroup);
        mem14->setObjectName(QStringLiteral("mem14"));
        mem14->setGeometry(QRect(50, 310, 50, 20));
        mem14->setFont(font3);
        mem14->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem14->setAlignment(Qt::AlignCenter);
        mem13 = new QLineEdit(memoryGroup);
        mem13->setObjectName(QStringLiteral("mem13"));
        mem13->setGeometry(QRect(50, 290, 50, 20));
        mem13->setFont(font3);
        mem13->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem13->setAlignment(Qt::AlignCenter);
        mem18 = new QLineEdit(memoryGroup);
        mem18->setObjectName(QStringLiteral("mem18"));
        mem18->setGeometry(QRect(50, 390, 50, 20));
        mem18->setFont(font3);
        mem18->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem18->setAlignment(Qt::AlignCenter);
        mem17 = new QLineEdit(memoryGroup);
        mem17->setObjectName(QStringLiteral("mem17"));
        mem17->setGeometry(QRect(50, 370, 50, 20));
        mem17->setFont(font3);
        mem17->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem17->setAlignment(Qt::AlignCenter);
        label_31 = new QLabel(memoryGroup);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(20, 210, 15, 20));
        label_31->setFont(font3);
        label_32 = new QLabel(memoryGroup);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(20, 30, 15, 20));
        label_32->setFont(font3);
        label_33 = new QLabel(memoryGroup);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(20, 130, 15, 20));
        label_33->setFont(font3);
        label_34 = new QLabel(memoryGroup);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(20, 170, 15, 20));
        label_34->setFont(font3);
        label_35 = new QLabel(memoryGroup);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(20, 190, 15, 20));
        label_35->setFont(font3);
        label_36 = new QLabel(memoryGroup);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(20, 70, 15, 20));
        label_36->setFont(font3);
        label_37 = new QLabel(memoryGroup);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(20, 110, 15, 20));
        label_37->setFont(font3);
        label_38 = new QLabel(memoryGroup);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(20, 50, 15, 20));
        label_38->setFont(font3);
        label_39 = new QLabel(memoryGroup);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(20, 90, 15, 20));
        label_39->setFont(font3);
        label_40 = new QLabel(memoryGroup);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(20, 150, 15, 20));
        label_40->setFont(font3);
        label_41 = new QLabel(memoryGroup);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(20, 410, 15, 20));
        label_41->setFont(font3);
        label_42 = new QLabel(memoryGroup);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(20, 270, 15, 20));
        label_42->setFont(font3);
        label_43 = new QLabel(memoryGroup);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(20, 250, 15, 20));
        label_43->setFont(font3);
        label_44 = new QLabel(memoryGroup);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(20, 230, 15, 20));
        label_44->setFont(font3);
        label_45 = new QLabel(memoryGroup);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(20, 330, 15, 20));
        label_45->setFont(font3);
        label_46 = new QLabel(memoryGroup);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(20, 370, 15, 20));
        label_46->setFont(font3);
        label_47 = new QLabel(memoryGroup);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(20, 390, 15, 20));
        label_47->setFont(font3);
        label_48 = new QLabel(memoryGroup);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(20, 310, 15, 20));
        label_48->setFont(font3);
        label_49 = new QLabel(memoryGroup);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(20, 290, 15, 20));
        label_49->setFont(font3);
        label_50 = new QLabel(memoryGroup);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(20, 350, 15, 20));
        label_50->setFont(font3);
        mem25 = new QLineEdit(memoryGroup);
        mem25->setObjectName(QStringLiteral("mem25"));
        mem25->setGeometry(QRect(160, 130, 50, 20));
        mem25->setFont(font3);
        mem25->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem25->setAlignment(Qt::AlignCenter);
        mem39 = new QLineEdit(memoryGroup);
        mem39->setObjectName(QStringLiteral("mem39"));
        mem39->setGeometry(QRect(160, 410, 50, 20));
        mem39->setFont(font3);
        mem39->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem39->setAlignment(Qt::AlignCenter);
        mem36 = new QLineEdit(memoryGroup);
        mem36->setObjectName(QStringLiteral("mem36"));
        mem36->setGeometry(QRect(160, 350, 50, 21));
        mem36->setFont(font3);
        mem36->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem36->setAlignment(Qt::AlignCenter);
        mem21 = new QLineEdit(memoryGroup);
        mem21->setObjectName(QStringLiteral("mem21"));
        mem21->setGeometry(QRect(160, 50, 50, 20));
        mem21->setFont(font3);
        mem21->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem21->setAlignment(Qt::AlignCenter);
        label_51 = new QLabel(memoryGroup);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(130, 70, 15, 20));
        label_51->setFont(font3);
        mem31 = new QLineEdit(memoryGroup);
        mem31->setObjectName(QStringLiteral("mem31"));
        mem31->setGeometry(QRect(160, 250, 50, 20));
        mem31->setFont(font3);
        mem31->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem31->setAlignment(Qt::AlignCenter);
        label_52 = new QLabel(memoryGroup);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(130, 350, 15, 20));
        label_52->setFont(font3);
        label_53 = new QLabel(memoryGroup);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(130, 150, 15, 20));
        label_53->setFont(font3);
        label_54 = new QLabel(memoryGroup);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(130, 110, 15, 20));
        label_54->setFont(font3);
        mem34 = new QLineEdit(memoryGroup);
        mem34->setObjectName(QStringLiteral("mem34"));
        mem34->setGeometry(QRect(160, 310, 50, 20));
        mem34->setFont(font3);
        mem34->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem34->setAlignment(Qt::AlignCenter);
        label_55 = new QLabel(memoryGroup);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(130, 50, 15, 20));
        label_55->setFont(font3);
        mem22 = new QLineEdit(memoryGroup);
        mem22->setObjectName(QStringLiteral("mem22"));
        mem22->setGeometry(QRect(160, 70, 50, 20));
        mem22->setFont(font3);
        mem22->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem22->setAlignment(Qt::AlignCenter);
        mem29 = new QLineEdit(memoryGroup);
        mem29->setObjectName(QStringLiteral("mem29"));
        mem29->setGeometry(QRect(160, 210, 50, 20));
        mem29->setFont(font3);
        mem29->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem29->setAlignment(Qt::AlignCenter);
        label_56 = new QLabel(memoryGroup);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(130, 170, 15, 20));
        label_56->setFont(font3);
        label_57 = new QLabel(memoryGroup);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(130, 230, 15, 20));
        label_57->setFont(font3);
        label_58 = new QLabel(memoryGroup);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(130, 190, 15, 20));
        label_58->setFont(font3);
        label_59 = new QLabel(memoryGroup);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(130, 410, 15, 20));
        label_59->setFont(font3);
        mem35 = new QLineEdit(memoryGroup);
        mem35->setObjectName(QStringLiteral("mem35"));
        mem35->setGeometry(QRect(160, 330, 50, 20));
        mem35->setFont(font3);
        mem35->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem35->setAlignment(Qt::AlignCenter);
        mem28 = new QLineEdit(memoryGroup);
        mem28->setObjectName(QStringLiteral("mem28"));
        mem28->setGeometry(QRect(160, 190, 50, 20));
        mem28->setFont(font3);
        mem28->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem28->setAlignment(Qt::AlignCenter);
        label_60 = new QLabel(memoryGroup);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(130, 290, 15, 20));
        label_60->setFont(font3);
        mem27 = new QLineEdit(memoryGroup);
        mem27->setObjectName(QStringLiteral("mem27"));
        mem27->setGeometry(QRect(160, 170, 50, 20));
        mem27->setFont(font3);
        mem27->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem27->setAlignment(Qt::AlignCenter);
        label_61 = new QLabel(memoryGroup);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(130, 210, 15, 20));
        label_61->setFont(font3);
        label_62 = new QLabel(memoryGroup);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(130, 130, 15, 20));
        label_62->setFont(font3);
        mem38 = new QLineEdit(memoryGroup);
        mem38->setObjectName(QStringLiteral("mem38"));
        mem38->setGeometry(QRect(160, 390, 50, 20));
        mem38->setFont(font3);
        mem38->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem38->setAlignment(Qt::AlignCenter);
        mem26 = new QLineEdit(memoryGroup);
        mem26->setObjectName(QStringLiteral("mem26"));
        mem26->setGeometry(QRect(160, 150, 50, 21));
        mem26->setFont(font3);
        mem26->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem26->setAlignment(Qt::AlignCenter);
        label_63 = new QLabel(memoryGroup);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(130, 250, 15, 20));
        label_63->setFont(font3);
        label_64 = new QLabel(memoryGroup);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(130, 310, 15, 20));
        label_64->setFont(font3);
        mem33 = new QLineEdit(memoryGroup);
        mem33->setObjectName(QStringLiteral("mem33"));
        mem33->setGeometry(QRect(160, 290, 50, 20));
        mem33->setFont(font3);
        mem33->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem33->setAlignment(Qt::AlignCenter);
        mem20 = new QLineEdit(memoryGroup);
        mem20->setObjectName(QStringLiteral("mem20"));
        mem20->setGeometry(QRect(160, 30, 50, 20));
        mem20->setFont(font3);
        mem20->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem20->setAlignment(Qt::AlignCenter);
        label_65 = new QLabel(memoryGroup);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(130, 90, 15, 20));
        label_65->setFont(font3);
        mem37 = new QLineEdit(memoryGroup);
        mem37->setObjectName(QStringLiteral("mem37"));
        mem37->setGeometry(QRect(160, 370, 50, 20));
        mem37->setFont(font3);
        mem37->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem37->setAlignment(Qt::AlignCenter);
        label_66 = new QLabel(memoryGroup);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(130, 370, 15, 20));
        label_66->setFont(font3);
        label_67 = new QLabel(memoryGroup);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(130, 330, 15, 20));
        label_67->setFont(font3);
        label_68 = new QLabel(memoryGroup);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(130, 390, 15, 20));
        label_68->setFont(font3);
        mem23 = new QLineEdit(memoryGroup);
        mem23->setObjectName(QStringLiteral("mem23"));
        mem23->setGeometry(QRect(160, 90, 50, 20));
        mem23->setFont(font3);
        mem23->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem23->setAlignment(Qt::AlignCenter);
        label_69 = new QLabel(memoryGroup);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(130, 30, 15, 20));
        label_69->setFont(font3);
        mem24 = new QLineEdit(memoryGroup);
        mem24->setObjectName(QStringLiteral("mem24"));
        mem24->setGeometry(QRect(160, 110, 50, 20));
        mem24->setFont(font3);
        mem24->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem24->setAlignment(Qt::AlignCenter);
        mem30 = new QLineEdit(memoryGroup);
        mem30->setObjectName(QStringLiteral("mem30"));
        mem30->setGeometry(QRect(160, 230, 50, 20));
        mem30->setFont(font3);
        mem30->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem30->setAlignment(Qt::AlignCenter);
        mem32 = new QLineEdit(memoryGroup);
        mem32->setObjectName(QStringLiteral("mem32"));
        mem32->setGeometry(QRect(160, 270, 50, 20));
        mem32->setFont(font3);
        mem32->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem32->setAlignment(Qt::AlignCenter);
        label_70 = new QLabel(memoryGroup);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(130, 270, 15, 20));
        label_70->setFont(font3);
        mem40 = new QLineEdit(memoryGroup);
        mem40->setObjectName(QStringLiteral("mem40"));
        mem40->setGeometry(QRect(270, 30, 50, 20));
        mem40->setFont(font3);
        mem40->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem40->setAlignment(Qt::AlignCenter);
        label_71 = new QLabel(memoryGroup);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(240, 210, 15, 20));
        label_71->setFont(font3);
        label_72 = new QLabel(memoryGroup);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(240, 350, 15, 20));
        label_72->setFont(font3);
        label_73 = new QLabel(memoryGroup);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(240, 190, 15, 20));
        label_73->setFont(font3);
        mem49 = new QLineEdit(memoryGroup);
        mem49->setObjectName(QStringLiteral("mem49"));
        mem49->setGeometry(QRect(270, 210, 50, 20));
        mem49->setFont(font3);
        mem49->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem49->setAlignment(Qt::AlignCenter);
        mem47 = new QLineEdit(memoryGroup);
        mem47->setObjectName(QStringLiteral("mem47"));
        mem47->setGeometry(QRect(270, 170, 50, 20));
        mem47->setFont(font3);
        mem47->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem47->setAlignment(Qt::AlignCenter);
        mem42 = new QLineEdit(memoryGroup);
        mem42->setObjectName(QStringLiteral("mem42"));
        mem42->setGeometry(QRect(270, 70, 50, 20));
        mem42->setFont(font3);
        mem42->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem42->setAlignment(Qt::AlignCenter);
        mem48 = new QLineEdit(memoryGroup);
        mem48->setObjectName(QStringLiteral("mem48"));
        mem48->setGeometry(QRect(270, 190, 50, 20));
        mem48->setFont(font3);
        mem48->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem48->setAlignment(Qt::AlignCenter);
        label_74 = new QLabel(memoryGroup);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(240, 370, 15, 20));
        label_74->setFont(font3);
        mem57 = new QLineEdit(memoryGroup);
        mem57->setObjectName(QStringLiteral("mem57"));
        mem57->setGeometry(QRect(270, 370, 50, 20));
        mem57->setFont(font3);
        mem57->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem57->setAlignment(Qt::AlignCenter);
        mem46 = new QLineEdit(memoryGroup);
        mem46->setObjectName(QStringLiteral("mem46"));
        mem46->setGeometry(QRect(270, 150, 50, 21));
        mem46->setFont(font3);
        mem46->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem46->setAlignment(Qt::AlignCenter);
        mem50 = new QLineEdit(memoryGroup);
        mem50->setObjectName(QStringLiteral("mem50"));
        mem50->setGeometry(QRect(270, 230, 50, 20));
        mem50->setFont(font3);
        mem50->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem50->setAlignment(Qt::AlignCenter);
        label_75 = new QLabel(memoryGroup);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(240, 310, 15, 20));
        label_75->setFont(font3);
        label_76 = new QLabel(memoryGroup);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(240, 410, 15, 20));
        label_76->setFont(font3);
        mem52 = new QLineEdit(memoryGroup);
        mem52->setObjectName(QStringLiteral("mem52"));
        mem52->setGeometry(QRect(270, 270, 50, 20));
        mem52->setFont(font3);
        mem52->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem52->setAlignment(Qt::AlignCenter);
        label_77 = new QLabel(memoryGroup);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(240, 230, 15, 20));
        label_77->setFont(font3);
        mem44 = new QLineEdit(memoryGroup);
        mem44->setObjectName(QStringLiteral("mem44"));
        mem44->setGeometry(QRect(270, 110, 50, 20));
        mem44->setFont(font3);
        mem44->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem44->setAlignment(Qt::AlignCenter);
        label_78 = new QLabel(memoryGroup);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(240, 250, 15, 20));
        label_78->setFont(font3);
        label_79 = new QLabel(memoryGroup);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(240, 50, 15, 20));
        label_79->setFont(font3);
        label_80 = new QLabel(memoryGroup);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(240, 150, 15, 20));
        label_80->setFont(font3);
        mem41 = new QLineEdit(memoryGroup);
        mem41->setObjectName(QStringLiteral("mem41"));
        mem41->setGeometry(QRect(270, 50, 50, 20));
        mem41->setFont(font3);
        mem41->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem41->setAlignment(Qt::AlignCenter);
        label_81 = new QLabel(memoryGroup);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(240, 110, 15, 20));
        label_81->setFont(font3);
        mem55 = new QLineEdit(memoryGroup);
        mem55->setObjectName(QStringLiteral("mem55"));
        mem55->setGeometry(QRect(270, 330, 50, 20));
        mem55->setFont(font3);
        mem55->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem55->setAlignment(Qt::AlignCenter);
        label_82 = new QLabel(memoryGroup);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(240, 130, 15, 20));
        label_82->setFont(font3);
        mem59 = new QLineEdit(memoryGroup);
        mem59->setObjectName(QStringLiteral("mem59"));
        mem59->setGeometry(QRect(270, 410, 50, 20));
        mem59->setFont(font3);
        mem59->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem59->setAlignment(Qt::AlignCenter);
        mem53 = new QLineEdit(memoryGroup);
        mem53->setObjectName(QStringLiteral("mem53"));
        mem53->setGeometry(QRect(270, 290, 50, 20));
        mem53->setFont(font3);
        mem53->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem53->setAlignment(Qt::AlignCenter);
        mem58 = new QLineEdit(memoryGroup);
        mem58->setObjectName(QStringLiteral("mem58"));
        mem58->setGeometry(QRect(270, 390, 50, 20));
        mem58->setFont(font3);
        mem58->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem58->setAlignment(Qt::AlignCenter);
        label_83 = new QLabel(memoryGroup);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(240, 390, 15, 20));
        label_83->setFont(font3);
        mem51 = new QLineEdit(memoryGroup);
        mem51->setObjectName(QStringLiteral("mem51"));
        mem51->setGeometry(QRect(270, 250, 50, 20));
        mem51->setFont(font3);
        mem51->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem51->setAlignment(Qt::AlignCenter);
        label_84 = new QLabel(memoryGroup);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(240, 290, 15, 20));
        label_84->setFont(font3);
        label_85 = new QLabel(memoryGroup);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(240, 70, 15, 20));
        label_85->setFont(font3);
        mem56 = new QLineEdit(memoryGroup);
        mem56->setObjectName(QStringLiteral("mem56"));
        mem56->setGeometry(QRect(270, 350, 50, 21));
        mem56->setFont(font3);
        mem56->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem56->setAlignment(Qt::AlignCenter);
        mem54 = new QLineEdit(memoryGroup);
        mem54->setObjectName(QStringLiteral("mem54"));
        mem54->setGeometry(QRect(270, 310, 50, 20));
        mem54->setFont(font3);
        mem54->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem54->setAlignment(Qt::AlignCenter);
        label_86 = new QLabel(memoryGroup);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(240, 330, 15, 20));
        label_86->setFont(font3);
        label_87 = new QLabel(memoryGroup);
        label_87->setObjectName(QStringLiteral("label_87"));
        label_87->setGeometry(QRect(240, 170, 15, 20));
        label_87->setFont(font3);
        mem45 = new QLineEdit(memoryGroup);
        mem45->setObjectName(QStringLiteral("mem45"));
        mem45->setGeometry(QRect(270, 130, 50, 20));
        mem45->setFont(font3);
        mem45->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem45->setAlignment(Qt::AlignCenter);
        label_88 = new QLabel(memoryGroup);
        label_88->setObjectName(QStringLiteral("label_88"));
        label_88->setGeometry(QRect(240, 270, 15, 20));
        label_88->setFont(font3);
        label_89 = new QLabel(memoryGroup);
        label_89->setObjectName(QStringLiteral("label_89"));
        label_89->setGeometry(QRect(240, 90, 15, 20));
        label_89->setFont(font3);
        mem43 = new QLineEdit(memoryGroup);
        mem43->setObjectName(QStringLiteral("mem43"));
        mem43->setGeometry(QRect(270, 90, 50, 20));
        mem43->setFont(font3);
        mem43->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem43->setAlignment(Qt::AlignCenter);
        label_90 = new QLabel(memoryGroup);
        label_90->setObjectName(QStringLiteral("label_90"));
        label_90->setGeometry(QRect(240, 30, 15, 20));
        label_90->setFont(font3);
        mem60 = new QLineEdit(memoryGroup);
        mem60->setObjectName(QStringLiteral("mem60"));
        mem60->setGeometry(QRect(380, 30, 50, 20));
        mem60->setFont(font3);
        mem60->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem60->setAlignment(Qt::AlignCenter);
        label_91 = new QLabel(memoryGroup);
        label_91->setObjectName(QStringLiteral("label_91"));
        label_91->setGeometry(QRect(350, 170, 15, 20));
        label_91->setFont(font3);
        label_92 = new QLabel(memoryGroup);
        label_92->setObjectName(QStringLiteral("label_92"));
        label_92->setGeometry(QRect(350, 330, 15, 20));
        label_92->setFont(font3);
        mem71 = new QLineEdit(memoryGroup);
        mem71->setObjectName(QStringLiteral("mem71"));
        mem71->setGeometry(QRect(380, 250, 50, 20));
        mem71->setFont(font3);
        mem71->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem71->setAlignment(Qt::AlignCenter);
        label_93 = new QLabel(memoryGroup);
        label_93->setObjectName(QStringLiteral("label_93"));
        label_93->setGeometry(QRect(350, 150, 15, 20));
        label_93->setFont(font3);
        label_94 = new QLabel(memoryGroup);
        label_94->setObjectName(QStringLiteral("label_94"));
        label_94->setGeometry(QRect(350, 190, 15, 20));
        label_94->setFont(font3);
        label_95 = new QLabel(memoryGroup);
        label_95->setObjectName(QStringLiteral("label_95"));
        label_95->setGeometry(QRect(350, 270, 15, 20));
        label_95->setFont(font3);
        mem63 = new QLineEdit(memoryGroup);
        mem63->setObjectName(QStringLiteral("mem63"));
        mem63->setGeometry(QRect(380, 90, 50, 20));
        mem63->setFont(font3);
        mem63->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem63->setAlignment(Qt::AlignCenter);
        label_96 = new QLabel(memoryGroup);
        label_96->setObjectName(QStringLiteral("label_96"));
        label_96->setGeometry(QRect(350, 210, 15, 20));
        label_96->setFont(font3);
        mem62 = new QLineEdit(memoryGroup);
        mem62->setObjectName(QStringLiteral("mem62"));
        mem62->setGeometry(QRect(380, 70, 50, 20));
        mem62->setFont(font3);
        mem62->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem62->setAlignment(Qt::AlignCenter);
        label_97 = new QLabel(memoryGroup);
        label_97->setObjectName(QStringLiteral("label_97"));
        label_97->setGeometry(QRect(350, 310, 15, 20));
        label_97->setFont(font3);
        label_98 = new QLabel(memoryGroup);
        label_98->setObjectName(QStringLiteral("label_98"));
        label_98->setGeometry(QRect(350, 350, 15, 20));
        label_98->setFont(font3);
        label_99 = new QLabel(memoryGroup);
        label_99->setObjectName(QStringLiteral("label_99"));
        label_99->setGeometry(QRect(350, 70, 15, 20));
        label_99->setFont(font3);
        label_100 = new QLabel(memoryGroup);
        label_100->setObjectName(QStringLiteral("label_100"));
        label_100->setGeometry(QRect(350, 90, 15, 20));
        label_100->setFont(font3);
        mem76 = new QLineEdit(memoryGroup);
        mem76->setObjectName(QStringLiteral("mem76"));
        mem76->setGeometry(QRect(380, 350, 50, 21));
        mem76->setFont(font3);
        mem76->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem76->setAlignment(Qt::AlignCenter);
        mem72 = new QLineEdit(memoryGroup);
        mem72->setObjectName(QStringLiteral("mem72"));
        mem72->setGeometry(QRect(380, 270, 50, 20));
        mem72->setFont(font3);
        mem72->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem72->setAlignment(Qt::AlignCenter);
        mem70 = new QLineEdit(memoryGroup);
        mem70->setObjectName(QStringLiteral("mem70"));
        mem70->setGeometry(QRect(380, 230, 50, 20));
        mem70->setFont(font3);
        mem70->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem70->setAlignment(Qt::AlignCenter);
        label_101 = new QLabel(memoryGroup);
        label_101->setObjectName(QStringLiteral("label_101"));
        label_101->setGeometry(QRect(350, 250, 15, 20));
        label_101->setFont(font3);
        mem68 = new QLineEdit(memoryGroup);
        mem68->setObjectName(QStringLiteral("mem68"));
        mem68->setGeometry(QRect(380, 190, 50, 20));
        mem68->setFont(font3);
        mem68->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem68->setAlignment(Qt::AlignCenter);
        label_102 = new QLabel(memoryGroup);
        label_102->setObjectName(QStringLiteral("label_102"));
        label_102->setGeometry(QRect(350, 290, 15, 20));
        label_102->setFont(font3);
        label_103 = new QLabel(memoryGroup);
        label_103->setObjectName(QStringLiteral("label_103"));
        label_103->setGeometry(QRect(350, 370, 15, 20));
        label_103->setFont(font3);
        mem67 = new QLineEdit(memoryGroup);
        mem67->setObjectName(QStringLiteral("mem67"));
        mem67->setGeometry(QRect(380, 170, 50, 20));
        mem67->setFont(font3);
        mem67->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem67->setAlignment(Qt::AlignCenter);
        mem66 = new QLineEdit(memoryGroup);
        mem66->setObjectName(QStringLiteral("mem66"));
        mem66->setGeometry(QRect(380, 150, 50, 21));
        mem66->setFont(font3);
        mem66->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem66->setAlignment(Qt::AlignCenter);
        mem74 = new QLineEdit(memoryGroup);
        mem74->setObjectName(QStringLiteral("mem74"));
        mem74->setGeometry(QRect(380, 310, 50, 20));
        mem74->setFont(font3);
        mem74->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem74->setAlignment(Qt::AlignCenter);
        mem77 = new QLineEdit(memoryGroup);
        mem77->setObjectName(QStringLiteral("mem77"));
        mem77->setGeometry(QRect(380, 370, 50, 20));
        mem77->setFont(font3);
        mem77->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem77->setAlignment(Qt::AlignCenter);
        mem65 = new QLineEdit(memoryGroup);
        mem65->setObjectName(QStringLiteral("mem65"));
        mem65->setGeometry(QRect(380, 130, 50, 20));
        mem65->setFont(font3);
        mem65->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem65->setAlignment(Qt::AlignCenter);
        label_104 = new QLabel(memoryGroup);
        label_104->setObjectName(QStringLiteral("label_104"));
        label_104->setGeometry(QRect(350, 130, 15, 20));
        label_104->setFont(font3);
        label_105 = new QLabel(memoryGroup);
        label_105->setObjectName(QStringLiteral("label_105"));
        label_105->setGeometry(QRect(350, 230, 15, 20));
        label_105->setFont(font3);
        mem75 = new QLineEdit(memoryGroup);
        mem75->setObjectName(QStringLiteral("mem75"));
        mem75->setGeometry(QRect(380, 330, 50, 20));
        mem75->setFont(font3);
        mem75->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem75->setAlignment(Qt::AlignCenter);
        mem78 = new QLineEdit(memoryGroup);
        mem78->setObjectName(QStringLiteral("mem78"));
        mem78->setGeometry(QRect(380, 390, 50, 20));
        mem78->setFont(font3);
        mem78->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem78->setAlignment(Qt::AlignCenter);
        label_106 = new QLabel(memoryGroup);
        label_106->setObjectName(QStringLiteral("label_106"));
        label_106->setGeometry(QRect(350, 50, 15, 20));
        label_106->setFont(font3);
        label_107 = new QLabel(memoryGroup);
        label_107->setObjectName(QStringLiteral("label_107"));
        label_107->setGeometry(QRect(350, 30, 15, 20));
        label_107->setFont(font3);
        mem79 = new QLineEdit(memoryGroup);
        mem79->setObjectName(QStringLiteral("mem79"));
        mem79->setGeometry(QRect(380, 410, 50, 20));
        mem79->setFont(font3);
        mem79->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem79->setAlignment(Qt::AlignCenter);
        label_108 = new QLabel(memoryGroup);
        label_108->setObjectName(QStringLiteral("label_108"));
        label_108->setGeometry(QRect(350, 110, 15, 20));
        label_108->setFont(font3);
        mem61 = new QLineEdit(memoryGroup);
        mem61->setObjectName(QStringLiteral("mem61"));
        mem61->setGeometry(QRect(380, 50, 50, 20));
        mem61->setFont(font3);
        mem61->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem61->setAlignment(Qt::AlignCenter);
        label_109 = new QLabel(memoryGroup);
        label_109->setObjectName(QStringLiteral("label_109"));
        label_109->setGeometry(QRect(350, 410, 15, 20));
        label_109->setFont(font3);
        mem73 = new QLineEdit(memoryGroup);
        mem73->setObjectName(QStringLiteral("mem73"));
        mem73->setGeometry(QRect(380, 290, 50, 20));
        mem73->setFont(font3);
        mem73->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem73->setAlignment(Qt::AlignCenter);
        mem64 = new QLineEdit(memoryGroup);
        mem64->setObjectName(QStringLiteral("mem64"));
        mem64->setGeometry(QRect(380, 110, 50, 20));
        mem64->setFont(font3);
        mem64->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem64->setAlignment(Qt::AlignCenter);
        label_110 = new QLabel(memoryGroup);
        label_110->setObjectName(QStringLiteral("label_110"));
        label_110->setGeometry(QRect(350, 390, 15, 20));
        label_110->setFont(font3);
        mem69 = new QLineEdit(memoryGroup);
        mem69->setObjectName(QStringLiteral("mem69"));
        mem69->setGeometry(QRect(380, 210, 50, 20));
        mem69->setFont(font3);
        mem69->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem69->setAlignment(Qt::AlignCenter);
        mem84 = new QLineEdit(memoryGroup);
        mem84->setObjectName(QStringLiteral("mem84"));
        mem84->setGeometry(QRect(490, 110, 50, 20));
        mem84->setFont(font3);
        mem84->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem84->setAlignment(Qt::AlignCenter);
        mem91 = new QLineEdit(memoryGroup);
        mem91->setObjectName(QStringLiteral("mem91"));
        mem91->setGeometry(QRect(490, 250, 50, 20));
        mem91->setFont(font3);
        mem91->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem91->setAlignment(Qt::AlignCenter);
        mem85 = new QLineEdit(memoryGroup);
        mem85->setObjectName(QStringLiteral("mem85"));
        mem85->setGeometry(QRect(490, 130, 50, 20));
        mem85->setFont(font3);
        mem85->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem85->setAlignment(Qt::AlignCenter);
        label_111 = new QLabel(memoryGroup);
        label_111->setObjectName(QStringLiteral("label_111"));
        label_111->setGeometry(QRect(460, 90, 15, 20));
        label_111->setFont(font3);
        mem90 = new QLineEdit(memoryGroup);
        mem90->setObjectName(QStringLiteral("mem90"));
        mem90->setGeometry(QRect(490, 230, 50, 20));
        mem90->setFont(font3);
        mem90->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem90->setAlignment(Qt::AlignCenter);
        mem87 = new QLineEdit(memoryGroup);
        mem87->setObjectName(QStringLiteral("mem87"));
        mem87->setGeometry(QRect(490, 170, 50, 20));
        mem87->setFont(font3);
        mem87->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem87->setAlignment(Qt::AlignCenter);
        mem88 = new QLineEdit(memoryGroup);
        mem88->setObjectName(QStringLiteral("mem88"));
        mem88->setGeometry(QRect(490, 190, 50, 20));
        mem88->setFont(font3);
        mem88->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem88->setAlignment(Qt::AlignCenter);
        mem81 = new QLineEdit(memoryGroup);
        mem81->setObjectName(QStringLiteral("mem81"));
        mem81->setGeometry(QRect(490, 50, 50, 20));
        mem81->setFont(font3);
        mem81->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem81->setAlignment(Qt::AlignCenter);
        label_112 = new QLabel(memoryGroup);
        label_112->setObjectName(QStringLiteral("label_112"));
        label_112->setGeometry(QRect(460, 330, 15, 20));
        label_112->setFont(font3);
        label_113 = new QLabel(memoryGroup);
        label_113->setObjectName(QStringLiteral("label_113"));
        label_113->setGeometry(QRect(460, 130, 15, 20));
        label_113->setFont(font3);
        label_114 = new QLabel(memoryGroup);
        label_114->setObjectName(QStringLiteral("label_114"));
        label_114->setGeometry(QRect(460, 70, 15, 20));
        label_114->setFont(font3);
        mem94 = new QLineEdit(memoryGroup);
        mem94->setObjectName(QStringLiteral("mem94"));
        mem94->setGeometry(QRect(490, 310, 50, 20));
        mem94->setFont(font3);
        mem94->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem94->setAlignment(Qt::AlignCenter);
        mem93 = new QLineEdit(memoryGroup);
        mem93->setObjectName(QStringLiteral("mem93"));
        mem93->setGeometry(QRect(490, 290, 50, 20));
        mem93->setFont(font3);
        mem93->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem93->setAlignment(Qt::AlignCenter);
        label_115 = new QLabel(memoryGroup);
        label_115->setObjectName(QStringLiteral("label_115"));
        label_115->setGeometry(QRect(460, 230, 15, 20));
        label_115->setFont(font3);
        label_116 = new QLabel(memoryGroup);
        label_116->setObjectName(QStringLiteral("label_116"));
        label_116->setGeometry(QRect(460, 310, 15, 20));
        label_116->setFont(font3);
        label_117 = new QLabel(memoryGroup);
        label_117->setObjectName(QStringLiteral("label_117"));
        label_117->setGeometry(QRect(460, 410, 15, 20));
        label_117->setFont(font3);
        label_118 = new QLabel(memoryGroup);
        label_118->setObjectName(QStringLiteral("label_118"));
        label_118->setGeometry(QRect(460, 50, 15, 20));
        label_118->setFont(font3);
        mem99 = new QLineEdit(memoryGroup);
        mem99->setObjectName(QStringLiteral("mem99"));
        mem99->setGeometry(QRect(490, 410, 50, 20));
        mem99->setFont(font3);
        mem99->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem99->setAlignment(Qt::AlignCenter);
        mem92 = new QLineEdit(memoryGroup);
        mem92->setObjectName(QStringLiteral("mem92"));
        mem92->setGeometry(QRect(490, 270, 50, 20));
        mem92->setFont(font3);
        mem92->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem92->setAlignment(Qt::AlignCenter);
        label_119 = new QLabel(memoryGroup);
        label_119->setObjectName(QStringLiteral("label_119"));
        label_119->setGeometry(QRect(460, 190, 15, 20));
        label_119->setFont(font3);
        mem80 = new QLineEdit(memoryGroup);
        mem80->setObjectName(QStringLiteral("mem80"));
        mem80->setGeometry(QRect(490, 30, 50, 20));
        mem80->setFont(font3);
        mem80->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem80->setAlignment(Qt::AlignCenter);
        label_120 = new QLabel(memoryGroup);
        label_120->setObjectName(QStringLiteral("label_120"));
        label_120->setGeometry(QRect(460, 30, 15, 20));
        label_120->setFont(font3);
        mem95 = new QLineEdit(memoryGroup);
        mem95->setObjectName(QStringLiteral("mem95"));
        mem95->setGeometry(QRect(490, 330, 50, 20));
        mem95->setFont(font3);
        mem95->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem95->setAlignment(Qt::AlignCenter);
        label_121 = new QLabel(memoryGroup);
        label_121->setObjectName(QStringLiteral("label_121"));
        label_121->setGeometry(QRect(460, 170, 15, 20));
        label_121->setFont(font3);
        label_122 = new QLabel(memoryGroup);
        label_122->setObjectName(QStringLiteral("label_122"));
        label_122->setGeometry(QRect(460, 110, 15, 20));
        label_122->setFont(font3);
        label_123 = new QLabel(memoryGroup);
        label_123->setObjectName(QStringLiteral("label_123"));
        label_123->setGeometry(QRect(460, 210, 15, 20));
        label_123->setFont(font3);
        mem98 = new QLineEdit(memoryGroup);
        mem98->setObjectName(QStringLiteral("mem98"));
        mem98->setGeometry(QRect(490, 390, 50, 20));
        mem98->setFont(font3);
        mem98->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem98->setAlignment(Qt::AlignCenter);
        label_124 = new QLabel(memoryGroup);
        label_124->setObjectName(QStringLiteral("label_124"));
        label_124->setGeometry(QRect(460, 350, 15, 20));
        label_124->setFont(font3);
        label_125 = new QLabel(memoryGroup);
        label_125->setObjectName(QStringLiteral("label_125"));
        label_125->setGeometry(QRect(460, 290, 15, 20));
        label_125->setFont(font3);
        label_126 = new QLabel(memoryGroup);
        label_126->setObjectName(QStringLiteral("label_126"));
        label_126->setGeometry(QRect(460, 150, 15, 20));
        label_126->setFont(font3);
        mem83 = new QLineEdit(memoryGroup);
        mem83->setObjectName(QStringLiteral("mem83"));
        mem83->setGeometry(QRect(490, 90, 50, 20));
        mem83->setFont(font3);
        mem83->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem83->setAlignment(Qt::AlignCenter);
        mem97 = new QLineEdit(memoryGroup);
        mem97->setObjectName(QStringLiteral("mem97"));
        mem97->setGeometry(QRect(490, 370, 50, 20));
        mem97->setFont(font3);
        mem97->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem97->setAlignment(Qt::AlignCenter);
        mem96 = new QLineEdit(memoryGroup);
        mem96->setObjectName(QStringLiteral("mem96"));
        mem96->setGeometry(QRect(490, 350, 50, 21));
        mem96->setFont(font3);
        mem96->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem96->setAlignment(Qt::AlignCenter);
        label_127 = new QLabel(memoryGroup);
        label_127->setObjectName(QStringLiteral("label_127"));
        label_127->setGeometry(QRect(460, 370, 15, 20));
        label_127->setFont(font3);
        mem89 = new QLineEdit(memoryGroup);
        mem89->setObjectName(QStringLiteral("mem89"));
        mem89->setGeometry(QRect(490, 210, 50, 20));
        mem89->setFont(font3);
        mem89->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem89->setAlignment(Qt::AlignCenter);
        label_128 = new QLabel(memoryGroup);
        label_128->setObjectName(QStringLiteral("label_128"));
        label_128->setGeometry(QRect(460, 390, 15, 20));
        label_128->setFont(font3);
        mem86 = new QLineEdit(memoryGroup);
        mem86->setObjectName(QStringLiteral("mem86"));
        mem86->setGeometry(QRect(490, 150, 50, 21));
        mem86->setFont(font3);
        mem86->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem86->setAlignment(Qt::AlignCenter);
        label_129 = new QLabel(memoryGroup);
        label_129->setObjectName(QStringLiteral("label_129"));
        label_129->setGeometry(QRect(460, 250, 15, 20));
        label_129->setFont(font3);
        mem82 = new QLineEdit(memoryGroup);
        mem82->setObjectName(QStringLiteral("mem82"));
        mem82->setGeometry(QRect(490, 70, 50, 20));
        mem82->setFont(font3);
        mem82->setInputMethodHints(Qt::ImhDigitsOnly|Qt::ImhFormattedNumbersOnly);
        mem82->setAlignment(Qt::AlignCenter);
        label_130 = new QLabel(memoryGroup);
        label_130->setObjectName(QStringLiteral("label_130"));
        label_130->setGeometry(QRect(460, 270, 15, 20));
        label_130->setFont(font3);
        clearMemBut = new QPushButton(memoryGroup);
        clearMemBut->setObjectName(QStringLiteral("clearMemBut"));
        clearMemBut->setGeometry(QRect(474, 440, 91, 21));
        clearMemBut->setFont(font1);
        mem1->raise();
        mem2->raise();
        mem5->raise();
        mem0->raise();
        mem6->raise();
        mem9->raise();
        mem4->raise();
        mem3->raise();
        mem8->raise();
        mem7->raise();
        mem11->raise();
        mem12->raise();
        mem15->raise();
        mem10->raise();
        mem16->raise();
        mem19->raise();
        mem14->raise();
        mem13->raise();
        mem18->raise();
        mem17->raise();
        label_31->raise();
        label_32->raise();
        label_33->raise();
        label_34->raise();
        label_35->raise();
        label_36->raise();
        label_37->raise();
        label_38->raise();
        label_39->raise();
        label_40->raise();
        label_41->raise();
        label_42->raise();
        label_43->raise();
        label_44->raise();
        label_45->raise();
        label_46->raise();
        label_47->raise();
        label_48->raise();
        label_49->raise();
        label_50->raise();
        mem25->raise();
        mem39->raise();
        mem36->raise();
        mem21->raise();
        label_51->raise();
        mem31->raise();
        label_52->raise();
        label_53->raise();
        label_54->raise();
        mem34->raise();
        label_55->raise();
        mem22->raise();
        mem29->raise();
        label_56->raise();
        label_57->raise();
        label_58->raise();
        label_59->raise();
        mem35->raise();
        mem28->raise();
        label_60->raise();
        mem27->raise();
        label_61->raise();
        label_62->raise();
        mem38->raise();
        mem26->raise();
        label_63->raise();
        label_64->raise();
        mem33->raise();
        mem20->raise();
        label_65->raise();
        mem37->raise();
        label_66->raise();
        label_67->raise();
        label_68->raise();
        mem23->raise();
        label_69->raise();
        mem24->raise();
        mem30->raise();
        mem32->raise();
        label_70->raise();
        mem40->raise();
        label_71->raise();
        label_72->raise();
        label_73->raise();
        mem49->raise();
        mem47->raise();
        mem42->raise();
        mem48->raise();
        label_74->raise();
        mem57->raise();
        mem46->raise();
        mem50->raise();
        label_75->raise();
        label_76->raise();
        mem52->raise();
        label_77->raise();
        mem44->raise();
        label_78->raise();
        label_79->raise();
        label_80->raise();
        mem41->raise();
        label_81->raise();
        mem55->raise();
        label_82->raise();
        mem59->raise();
        mem53->raise();
        mem58->raise();
        label_83->raise();
        mem51->raise();
        label_84->raise();
        label_85->raise();
        mem56->raise();
        mem54->raise();
        label_86->raise();
        label_87->raise();
        mem45->raise();
        label_88->raise();
        label_89->raise();
        mem43->raise();
        label_90->raise();
        mem60->raise();
        label_91->raise();
        label_92->raise();
        mem71->raise();
        label_93->raise();
        label_94->raise();
        label_95->raise();
        mem63->raise();
        label_96->raise();
        mem62->raise();
        label_97->raise();
        label_98->raise();
        label_99->raise();
        label_100->raise();
        mem76->raise();
        mem72->raise();
        mem70->raise();
        label_101->raise();
        mem68->raise();
        label_102->raise();
        label_103->raise();
        mem67->raise();
        mem66->raise();
        mem74->raise();
        mem77->raise();
        mem65->raise();
        label_104->raise();
        label_105->raise();
        mem75->raise();
        mem78->raise();
        label_106->raise();
        label_107->raise();
        mem79->raise();
        label_108->raise();
        mem61->raise();
        label_109->raise();
        mem73->raise();
        mem64->raise();
        label_110->raise();
        mem69->raise();
        mem84->raise();
        mem91->raise();
        mem85->raise();
        label_111->raise();
        mem90->raise();
        mem87->raise();
        mem88->raise();
        mem81->raise();
        label_112->raise();
        label_113->raise();
        label_114->raise();
        mem94->raise();
        mem93->raise();
        label_115->raise();
        label_116->raise();
        label_117->raise();
        label_118->raise();
        mem99->raise();
        mem92->raise();
        label_119->raise();
        mem80->raise();
        label_120->raise();
        mem95->raise();
        label_121->raise();
        label_122->raise();
        label_123->raise();
        mem98->raise();
        label_124->raise();
        label_125->raise();
        label_126->raise();
        mem83->raise();
        mem97->raise();
        mem96->raise();
        label_127->raise();
        mem89->raise();
        label_128->raise();
        mem86->raise();
        label_129->raise();
        mem82->raise();
        label_130->raise();
        clearMemBut->raise();
        label_131 = new QLabel(centralWidget);
        label_131->setObjectName(QStringLiteral("label_131"));
        label_131->setGeometry(QRect(20, 10, 191, 81));
        label_131->setFont(font);
        saveLoadWidget = new QWidget(centralWidget);
        saveLoadWidget->setObjectName(QStringLiteral("saveLoadWidget"));
        saveLoadWidget->setGeometry(QRect(170, 560, 301, 91));
        okButton = new QPushButton(saveLoadWidget);
        okButton->setObjectName(QStringLiteral("okButton"));
        okButton->setGeometry(QRect(120, 60, 75, 23));
        cancelButton = new QPushButton(saveLoadWidget);
        cancelButton->setObjectName(QStringLiteral("cancelButton"));
        cancelButton->setGeometry(QRect(200, 60, 75, 23));
        fileNameInput = new QLineEdit(saveLoadWidget);
        fileNameInput->setObjectName(QStringLiteral("fileNameInput"));
        fileNameInput->setGeometry(QRect(70, 30, 221, 21));
        label_21 = new QLabel(saveLoadWidget);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 30, 61, 16));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 835, 21));
        fileMenu = new QMenu(menuBar);
        fileMenu->setObjectName(QStringLiteral("fileMenu"));
        helpMenu = new QMenu(menuBar);
        helpMenu->setObjectName(QStringLiteral("helpMenu"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        QWidget::setTabOrder(AC1, AC2);
        QWidget::setTabOrder(AC2, AC3);
        QWidget::setTabOrder(AC3, AC4);
        QWidget::setTabOrder(AC4, IR1);
        QWidget::setTabOrder(IR1, IR2);
        QWidget::setTabOrder(IR2, IR3);
        QWidget::setTabOrder(IR3, PC1);
        QWidget::setTabOrder(PC1, PC2);
        QWidget::setTabOrder(PC2, runBtn);
        QWidget::setTabOrder(runBtn, stepBtn);
        QWidget::setTabOrder(stepBtn, clearCPUBut);
        QWidget::setTabOrder(clearCPUBut, clearAllBut);
        QWidget::setTabOrder(clearAllBut, IC1);
        QWidget::setTabOrder(IC1, IC2);
        QWidget::setTabOrder(IC2, IC3);
        QWidget::setTabOrder(IC3, IC4);
        QWidget::setTabOrder(IC4, IC5);
        QWidget::setTabOrder(IC5, IC6);
        QWidget::setTabOrder(IC6, IC7);
        QWidget::setTabOrder(IC7, IC8);
        QWidget::setTabOrder(IC8, IC9);
        QWidget::setTabOrder(IC9, IC10);
        QWidget::setTabOrder(IC10, clearInBut);
        QWidget::setTabOrder(clearInBut, OC1);
        QWidget::setTabOrder(OC1, OC2);
        QWidget::setTabOrder(OC2, OC3);
        QWidget::setTabOrder(OC3, OC4);
        QWidget::setTabOrder(OC4, OC5);
        QWidget::setTabOrder(OC5, OC6);
        QWidget::setTabOrder(OC6, OC7);
        QWidget::setTabOrder(OC7, OC8);
        QWidget::setTabOrder(OC8, OC9);
        QWidget::setTabOrder(OC9, OC10);
        QWidget::setTabOrder(OC10, clearOutBut);
        QWidget::setTabOrder(clearOutBut, mem0);
        QWidget::setTabOrder(mem0, mem1);
        QWidget::setTabOrder(mem1, mem2);
        QWidget::setTabOrder(mem2, mem3);
        QWidget::setTabOrder(mem3, mem4);
        QWidget::setTabOrder(mem4, mem5);
        QWidget::setTabOrder(mem5, mem6);
        QWidget::setTabOrder(mem6, mem7);
        QWidget::setTabOrder(mem7, mem8);
        QWidget::setTabOrder(mem8, mem9);
        QWidget::setTabOrder(mem9, mem10);
        QWidget::setTabOrder(mem10, mem11);
        QWidget::setTabOrder(mem11, mem12);
        QWidget::setTabOrder(mem12, mem13);
        QWidget::setTabOrder(mem13, mem14);
        QWidget::setTabOrder(mem14, mem15);
        QWidget::setTabOrder(mem15, mem16);
        QWidget::setTabOrder(mem16, mem17);
        QWidget::setTabOrder(mem17, mem18);
        QWidget::setTabOrder(mem18, mem19);
        QWidget::setTabOrder(mem19, mem20);
        QWidget::setTabOrder(mem20, mem21);
        QWidget::setTabOrder(mem21, mem22);
        QWidget::setTabOrder(mem22, mem23);
        QWidget::setTabOrder(mem23, mem24);
        QWidget::setTabOrder(mem24, mem25);
        QWidget::setTabOrder(mem25, mem26);
        QWidget::setTabOrder(mem26, mem27);
        QWidget::setTabOrder(mem27, mem28);
        QWidget::setTabOrder(mem28, mem29);
        QWidget::setTabOrder(mem29, mem30);
        QWidget::setTabOrder(mem30, mem31);
        QWidget::setTabOrder(mem31, mem32);
        QWidget::setTabOrder(mem32, mem33);
        QWidget::setTabOrder(mem33, mem34);
        QWidget::setTabOrder(mem34, mem35);
        QWidget::setTabOrder(mem35, mem36);
        QWidget::setTabOrder(mem36, mem37);
        QWidget::setTabOrder(mem37, mem38);
        QWidget::setTabOrder(mem38, mem39);
        QWidget::setTabOrder(mem39, mem40);
        QWidget::setTabOrder(mem40, mem41);
        QWidget::setTabOrder(mem41, mem42);
        QWidget::setTabOrder(mem42, mem43);
        QWidget::setTabOrder(mem43, mem44);
        QWidget::setTabOrder(mem44, mem45);
        QWidget::setTabOrder(mem45, mem46);
        QWidget::setTabOrder(mem46, mem47);
        QWidget::setTabOrder(mem47, mem48);
        QWidget::setTabOrder(mem48, mem49);
        QWidget::setTabOrder(mem49, mem50);
        QWidget::setTabOrder(mem50, mem51);
        QWidget::setTabOrder(mem51, mem52);
        QWidget::setTabOrder(mem52, mem53);
        QWidget::setTabOrder(mem53, mem54);
        QWidget::setTabOrder(mem54, mem55);
        QWidget::setTabOrder(mem55, mem56);
        QWidget::setTabOrder(mem56, mem57);
        QWidget::setTabOrder(mem57, mem58);
        QWidget::setTabOrder(mem58, mem59);
        QWidget::setTabOrder(mem59, mem60);
        QWidget::setTabOrder(mem60, mem61);
        QWidget::setTabOrder(mem61, mem62);
        QWidget::setTabOrder(mem62, mem63);
        QWidget::setTabOrder(mem63, mem64);
        QWidget::setTabOrder(mem64, mem65);
        QWidget::setTabOrder(mem65, mem66);
        QWidget::setTabOrder(mem66, mem67);
        QWidget::setTabOrder(mem67, mem68);
        QWidget::setTabOrder(mem68, mem69);
        QWidget::setTabOrder(mem69, mem70);
        QWidget::setTabOrder(mem70, mem71);
        QWidget::setTabOrder(mem71, mem72);
        QWidget::setTabOrder(mem72, mem73);
        QWidget::setTabOrder(mem73, mem74);
        QWidget::setTabOrder(mem74, mem75);
        QWidget::setTabOrder(mem75, mem76);
        QWidget::setTabOrder(mem76, mem77);
        QWidget::setTabOrder(mem77, mem78);
        QWidget::setTabOrder(mem78, mem79);
        QWidget::setTabOrder(mem79, mem80);
        QWidget::setTabOrder(mem80, mem81);
        QWidget::setTabOrder(mem81, mem82);
        QWidget::setTabOrder(mem82, mem83);
        QWidget::setTabOrder(mem83, mem84);
        QWidget::setTabOrder(mem84, mem85);
        QWidget::setTabOrder(mem85, mem86);
        QWidget::setTabOrder(mem86, mem87);
        QWidget::setTabOrder(mem87, mem88);
        QWidget::setTabOrder(mem88, mem89);
        QWidget::setTabOrder(mem89, mem90);
        QWidget::setTabOrder(mem90, mem91);
        QWidget::setTabOrder(mem91, mem92);
        QWidget::setTabOrder(mem92, mem93);
        QWidget::setTabOrder(mem93, mem94);
        QWidget::setTabOrder(mem94, mem95);
        QWidget::setTabOrder(mem95, mem96);
        QWidget::setTabOrder(mem96, mem97);
        QWidget::setTabOrder(mem97, mem98);
        QWidget::setTabOrder(mem98, mem99);
        QWidget::setTabOrder(mem99, clearMemBut);

        menuBar->addAction(fileMenu->menuAction());
        menuBar->addAction(helpMenu->menuAction());
        fileMenu->addAction(actionSave_File);
        fileMenu->addAction(actionLoad_File);
        fileMenu->addAction(actionExit);
        helpMenu->addAction(actionHelp);
        helpMenu->addAction(actionUser_Manual);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        actionNew_File->setText(QApplication::translate("MainWindow", "New File", 0));
        actionSave_File->setText(QApplication::translate("MainWindow", "Save File", 0));
        actionLoad_File->setText(QApplication::translate("MainWindow", "Load File", 0));
        actionExit->setText(QApplication::translate("MainWindow", "Exit", 0));
        actionHelp->setText(QApplication::translate("MainWindow", "Help", 0));
        actionUser_Manual->setText(QApplication::translate("MainWindow", "User Manual", 0));
        CPUGroup->setTitle(QApplication::translate("MainWindow", "CPU", 0));
        ACGroup->setTitle(QApplication::translate("MainWindow", "AC", 0));
        IRGroup->setTitle(QApplication::translate("MainWindow", "IR", 0));
        runBtn->setText(QApplication::translate("MainWindow", "Run", 0));
        stepBtn->setText(QApplication::translate("MainWindow", "Step", 0));
        clearCPUBut->setText(QApplication::translate("MainWindow", "Clear CPU", 0));
        clearAllBut->setText(QApplication::translate("MainWindow", "Clear ALL", 0));
        PCGroup->setTitle(QApplication::translate("MainWindow", "PC", 0));
        InputGroup->setTitle(QApplication::translate("MainWindow", "Input Cards (IC)", 0));
        label->setText(QApplication::translate("MainWindow", "1", 0));
        label_2->setText(QApplication::translate("MainWindow", "2", 0));
        label_3->setText(QApplication::translate("MainWindow", "3", 0));
        label_4->setText(QApplication::translate("MainWindow", "4", 0));
        label_5->setText(QApplication::translate("MainWindow", "5", 0));
        label_6->setText(QApplication::translate("MainWindow", "6", 0));
        label_7->setText(QApplication::translate("MainWindow", "7", 0));
        label_8->setText(QApplication::translate("MainWindow", "8", 0));
        label_9->setText(QApplication::translate("MainWindow", "9", 0));
        label_10->setText(QApplication::translate("MainWindow", "10", 0));
        resetInBtn->setText(QApplication::translate("MainWindow", "Reset Input", 0));
        clearInBut->setText(QApplication::translate("MainWindow", "Clear Input", 0));
        OutputGroup->setTitle(QApplication::translate("MainWindow", "Output Cards (OC)", 0));
        label_11->setText(QApplication::translate("MainWindow", "1", 0));
        label_12->setText(QApplication::translate("MainWindow", "2", 0));
        label_13->setText(QApplication::translate("MainWindow", "3", 0));
        label_14->setText(QApplication::translate("MainWindow", "4", 0));
        label_15->setText(QApplication::translate("MainWindow", "5", 0));
        label_16->setText(QApplication::translate("MainWindow", "6", 0));
        label_17->setText(QApplication::translate("MainWindow", "7", 0));
        label_18->setText(QApplication::translate("MainWindow", "8", 0));
        label_19->setText(QApplication::translate("MainWindow", "9", 0));
        label_20->setText(QApplication::translate("MainWindow", "10", 0));
        clearOutBut->setText(QApplication::translate("MainWindow", "Clear Output", 0));
        memoryGroup->setTitle(QApplication::translate("MainWindow", "Memory", 0));
        mem0->setText(QApplication::translate("MainWindow", "001", 0));
        label_31->setText(QApplication::translate("MainWindow", "09", 0));
        label_32->setText(QApplication::translate("MainWindow", "00", 0));
        label_33->setText(QApplication::translate("MainWindow", "05", 0));
        label_34->setText(QApplication::translate("MainWindow", "07", 0));
        label_35->setText(QApplication::translate("MainWindow", "08", 0));
        label_36->setText(QApplication::translate("MainWindow", "02", 0));
        label_37->setText(QApplication::translate("MainWindow", "04", 0));
        label_38->setText(QApplication::translate("MainWindow", "01", 0));
        label_39->setText(QApplication::translate("MainWindow", "03", 0));
        label_40->setText(QApplication::translate("MainWindow", "06", 0));
        label_41->setText(QApplication::translate("MainWindow", "19", 0));
        label_42->setText(QApplication::translate("MainWindow", "12", 0));
        label_43->setText(QApplication::translate("MainWindow", "11", 0));
        label_44->setText(QApplication::translate("MainWindow", "10", 0));
        label_45->setText(QApplication::translate("MainWindow", "15", 0));
        label_46->setText(QApplication::translate("MainWindow", "17", 0));
        label_47->setText(QApplication::translate("MainWindow", "18", 0));
        label_48->setText(QApplication::translate("MainWindow", "14", 0));
        label_49->setText(QApplication::translate("MainWindow", "13", 0));
        label_50->setText(QApplication::translate("MainWindow", "16", 0));
        label_51->setText(QApplication::translate("MainWindow", "22", 0));
        label_52->setText(QApplication::translate("MainWindow", "36", 0));
        label_53->setText(QApplication::translate("MainWindow", "26", 0));
        label_54->setText(QApplication::translate("MainWindow", "24", 0));
        label_55->setText(QApplication::translate("MainWindow", "21", 0));
        label_56->setText(QApplication::translate("MainWindow", "27", 0));
        label_57->setText(QApplication::translate("MainWindow", "30", 0));
        label_58->setText(QApplication::translate("MainWindow", "28", 0));
        label_59->setText(QApplication::translate("MainWindow", "39", 0));
        label_60->setText(QApplication::translate("MainWindow", "33", 0));
        label_61->setText(QApplication::translate("MainWindow", "29", 0));
        label_62->setText(QApplication::translate("MainWindow", "25", 0));
        label_63->setText(QApplication::translate("MainWindow", "31", 0));
        label_64->setText(QApplication::translate("MainWindow", "34", 0));
        label_65->setText(QApplication::translate("MainWindow", "23", 0));
        label_66->setText(QApplication::translate("MainWindow", "37", 0));
        label_67->setText(QApplication::translate("MainWindow", "35", 0));
        label_68->setText(QApplication::translate("MainWindow", "38", 0));
        label_69->setText(QApplication::translate("MainWindow", "20", 0));
        label_70->setText(QApplication::translate("MainWindow", "32", 0));
        label_71->setText(QApplication::translate("MainWindow", "49", 0));
        label_72->setText(QApplication::translate("MainWindow", "56", 0));
        label_73->setText(QApplication::translate("MainWindow", "48", 0));
        label_74->setText(QApplication::translate("MainWindow", "57", 0));
        label_75->setText(QApplication::translate("MainWindow", "54", 0));
        label_76->setText(QApplication::translate("MainWindow", "59", 0));
        label_77->setText(QApplication::translate("MainWindow", "50", 0));
        label_78->setText(QApplication::translate("MainWindow", "51", 0));
        label_79->setText(QApplication::translate("MainWindow", "41", 0));
        label_80->setText(QApplication::translate("MainWindow", "46", 0));
        label_81->setText(QApplication::translate("MainWindow", "44", 0));
        label_82->setText(QApplication::translate("MainWindow", "45", 0));
        label_83->setText(QApplication::translate("MainWindow", "58", 0));
        label_84->setText(QApplication::translate("MainWindow", "53", 0));
        label_85->setText(QApplication::translate("MainWindow", "42", 0));
        label_86->setText(QApplication::translate("MainWindow", "55", 0));
        label_87->setText(QApplication::translate("MainWindow", "47", 0));
        label_88->setText(QApplication::translate("MainWindow", "52", 0));
        label_89->setText(QApplication::translate("MainWindow", "43", 0));
        label_90->setText(QApplication::translate("MainWindow", "40", 0));
        label_91->setText(QApplication::translate("MainWindow", "67", 0));
        label_92->setText(QApplication::translate("MainWindow", "75", 0));
        label_93->setText(QApplication::translate("MainWindow", "66", 0));
        label_94->setText(QApplication::translate("MainWindow", "68", 0));
        label_95->setText(QApplication::translate("MainWindow", "72", 0));
        label_96->setText(QApplication::translate("MainWindow", "69", 0));
        label_97->setText(QApplication::translate("MainWindow", "74", 0));
        label_98->setText(QApplication::translate("MainWindow", "76", 0));
        label_99->setText(QApplication::translate("MainWindow", "62", 0));
        label_100->setText(QApplication::translate("MainWindow", "63", 0));
        label_101->setText(QApplication::translate("MainWindow", "71", 0));
        label_102->setText(QApplication::translate("MainWindow", "73", 0));
        label_103->setText(QApplication::translate("MainWindow", "77", 0));
        label_104->setText(QApplication::translate("MainWindow", "65", 0));
        label_105->setText(QApplication::translate("MainWindow", "70", 0));
        label_106->setText(QApplication::translate("MainWindow", "61", 0));
        label_107->setText(QApplication::translate("MainWindow", "60", 0));
        label_108->setText(QApplication::translate("MainWindow", "64", 0));
        label_109->setText(QApplication::translate("MainWindow", "79", 0));
        label_110->setText(QApplication::translate("MainWindow", "78", 0));
        label_111->setText(QApplication::translate("MainWindow", "83", 0));
        label_112->setText(QApplication::translate("MainWindow", "95", 0));
        label_113->setText(QApplication::translate("MainWindow", "85", 0));
        label_114->setText(QApplication::translate("MainWindow", "82", 0));
        label_115->setText(QApplication::translate("MainWindow", "90", 0));
        label_116->setText(QApplication::translate("MainWindow", "94", 0));
        label_117->setText(QApplication::translate("MainWindow", "99", 0));
        label_118->setText(QApplication::translate("MainWindow", "81", 0));
        label_119->setText(QApplication::translate("MainWindow", "88", 0));
        label_120->setText(QApplication::translate("MainWindow", "80", 0));
        label_121->setText(QApplication::translate("MainWindow", "87", 0));
        label_122->setText(QApplication::translate("MainWindow", "84", 0));
        label_123->setText(QApplication::translate("MainWindow", "89", 0));
        mem98->setText(QString());
        label_124->setText(QApplication::translate("MainWindow", "96", 0));
        label_125->setText(QApplication::translate("MainWindow", "93", 0));
        label_126->setText(QApplication::translate("MainWindow", "86", 0));
        label_127->setText(QApplication::translate("MainWindow", "97", 0));
        label_128->setText(QApplication::translate("MainWindow", "98", 0));
        label_129->setText(QApplication::translate("MainWindow", "91", 0));
        label_130->setText(QApplication::translate("MainWindow", "92", 0));
        clearMemBut->setText(QApplication::translate("MainWindow", "Clear Memory", 0));
        label_131->setText(QApplication::translate("MainWindow", "CPU - Central Processing Unit\n"
"AC - Accumulator\n"
"IR - Instruction Register\n"
"PC - Prgoram Counter", 0));
        okButton->setText(QApplication::translate("MainWindow", "OK", 0));
        cancelButton->setText(QApplication::translate("MainWindow", "Cancel", 0));
        label_21->setText(QApplication::translate("MainWindow", "File Name:", 0));
        fileMenu->setTitle(QApplication::translate("MainWindow", "File", 0));
        helpMenu->setTitle(QApplication::translate("MainWindow", "Help", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
